<?php
/**
 * SubscriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Thip
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ThiemeMeulenhoff Content API
 *
 * Concept of an API to get the content from the publication service.
 *
 * OpenAPI spec version: 0.8.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Thip;

use PHPUnit\Framework\TestCase;

/**
 * SubscriptionTest Class Doc Comment
 *
 * @category    Class
 * @description Subscription
 * @package     Thip
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SubscriptionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Subscription"
     */
    public function testSubscription()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "callback_url"
     */
    public function testPropertyCallbackUrl()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }
}
