<?php
/**
 * TermsGroupTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Thip
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ThiemeMeulenhoff Content API
 *
 * Concept of an API to get the content from the publication service.
 *
 * OpenAPI spec version: 0.8.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Thip;

use PHPUnit\Framework\TestCase;

/**
 * TermsGroupTest Class Doc Comment
 *
 * @category    Class
 * @description TermsGroup
 * @package     Thip
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TermsGroupTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TermsGroup"
     */
    public function testTermsGroup()
    {
    }

    /**
     * Test attribute "content_identifier"
     */
    public function testPropertyContentIdentifier()
    {
    }

    /**
     * Test attribute "thed_content_identifier"
     */
    public function testPropertyThedContentIdentifier()
    {
    }

    /**
     * Test attribute "digital_resource_type"
     */
    public function testPropertyDigitalResourceType()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "intendedend_user_role"
     */
    public function testPropertyIntendedendUserRole()
    {
    }

    /**
     * Test attribute "typical_learning_time"
     */
    public function testPropertyTypicalLearningTime()
    {
    }

    /**
     * Test attribute "learning_level"
     */
    public function testPropertyLearningLevel()
    {
    }

    /**
     * Test attribute "lam_cells"
     */
    public function testPropertyLamCells()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "short_title"
     */
    public function testPropertyShortTitle()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "background_image"
     */
    public function testPropertyBackgroundImage()
    {
    }

    /**
     * Test attribute "parent"
     */
    public function testPropertyParent()
    {
    }

    /**
     * Test attribute "children"
     */
    public function testPropertyChildren()
    {
    }

    /**
     * Test attribute "related_digital_resources"
     */
    public function testPropertyRelatedDigitalResources()
    {
    }

    /**
     * Test attribute "terms_refs"
     */
    public function testPropertyTermsRefs()
    {
    }

    /**
     * Test attribute "keywords"
     */
    public function testPropertyKeywords()
    {
    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "assets"
     */
    public function testPropertyAssets()
    {
    }

    /**
     * Test attribute "methods"
     */
    public function testPropertyMethods()
    {
    }

    /**
     * Test attribute "thiemo_keywords"
     */
    public function testPropertyThiemoKeywords()
    {
    }

    /**
     * Test attribute "thiemo_tags"
     */
    public function testPropertyThiemoTags()
    {
    }

    /**
     * Test attribute "thiemo_subject"
     */
    public function testPropertyThiemoSubject()
    {
    }

    /**
     * Test attribute "thiemo_method"
     */
    public function testPropertyThiemoMethod()
    {
    }

    /**
     * Test attribute "thiemo_year"
     */
    public function testPropertyThiemoYear()
    {
    }

    /**
     * Test attribute "thiemo_schooltas_isbn"
     */
    public function testPropertyThiemoSchooltasIsbn()
    {
    }

    /**
     * Test attribute "thiemo_schooltas_page"
     */
    public function testPropertyThiemoSchooltasPage()
    {
    }

    /**
     * Test attribute "thiemo_content_type"
     */
    public function testPropertyThiemoContentType()
    {
    }

    /**
     * Test attribute "thiemo_is_locked"
     */
    public function testPropertyThiemoIsLocked()
    {
    }

    /**
     * Test attribute "thiemo_source_logo"
     */
    public function testPropertyThiemoSourceLogo()
    {
    }

    /**
     * Test attribute "term_items"
     */
    public function testPropertyTermItems()
    {
    }
}
