<?php
/**
 * ContentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Thip
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ThiemeMeulenhoff Content API
 *
 * Concept of an API to get the content from the publication service.
 *
 * OpenAPI spec version: 0.8.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Thip;

use \Thip\Configuration;
use \Thip\ApiException;
use \Thip\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ContentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Thip
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for publicationServiceApplicationControllerCourseApiControllerContent
     *
     * Get content of a publication. The content can be queried at any level. With a flag you can ask to include the children (content tree). With a flag you can chose to include the content itself (if you have rights to do so)..
     *
     */
    public function testPublicationServiceApplicationControllerCourseApiControllerContent()
    {
    }

    /**
     * Test case for publicationServiceApplicationControllerCourseApiControllerFilter
     *
     * Get specific content from a publication, filtered with several optional filters. Choose at least one filter, otherwise this api does nothing..
     *
     */
    public function testPublicationServiceApplicationControllerCourseApiControllerFilter()
    {
    }

    /**
     * Test case for publicationServiceApplicationControllerCourseApiControllerXml
     *
     * Get Edition XML of the newest publication in a stream..
     *
     */
    public function testPublicationServiceApplicationControllerCourseApiControllerXml()
    {
    }
}
