<?php
/**
 * CourseApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Thip
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ThiemeMeulenhoff Content API
 *
 * Concept of an API to get the content from the publication service.
 *
 * OpenAPI spec version: 0.8.5
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Thip;

use \Thip\Configuration;
use \Thip\ApiException;
use \Thip\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CourseApiTest Class Doc Comment
 *
 * @category Class
 * @package  Thip
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CourseApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for publicationServiceApplicationControllerCourseApiControllerIndexAction
     *
     * This call can be used to get the list of available courses for this user.
     *
     */
    public function testPublicationServiceApplicationControllerCourseApiControllerIndexAction()
    {
    }

    /**
     * Test case for publicationServiceApplicationControllerSubscriptionApiControllerCdelete
     *
     * Unsubscribe all callbacks.
     *
     */
    public function testPublicationServiceApplicationControllerSubscriptionApiControllerCdelete()
    {
    }

    /**
     * Test case for publicationServiceApplicationControllerSubscriptionApiControllerCget
     *
     * Get all callbacks.
     *
     */
    public function testPublicationServiceApplicationControllerSubscriptionApiControllerCget()
    {
    }

    /**
     * Test case for publicationServiceApplicationControllerSubscriptionApiControllerDelete
     *
     * Get specific callback by subscriptionId.
     *
     */
    public function testPublicationServiceApplicationControllerSubscriptionApiControllerDelete()
    {
    }

    /**
     * Test case for publicationServiceApplicationControllerSubscriptionApiControllerGet
     *
     * Get specific callback by subscriptionId.
     *
     */
    public function testPublicationServiceApplicationControllerSubscriptionApiControllerGet()
    {
    }

    /**
     * Test case for publicationServiceApplicationControllerSubscriptionApiControllerPost
     *
     * Subscribes a client to receive course change notifications.
     *
     */
    public function testPublicationServiceApplicationControllerSubscriptionApiControllerPost()
    {
    }
}
